# Generated by Django 2.0.2 on 2018-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_import_vendors_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(default='Pool', max_length=128),
        ),
        migrations.AlterField(
            model_name='pool',
            name='vehicle',
            field=models.CharField(choices=[('OASIS_SB', 'OASIS Small Business'), ('OASIS', 'OASIS Unrestricted'), ('HCATS_SB', 'HCATS Small Business'), ('HCATS', 'HCATS Unrestricted')], max_length=20),
        ),
    ]
