# Generated by Django 2.0.2 on 2018-03-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180301_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='vehicle',
            field=models.CharField(choices=[('OASIS_SB', 'OASIS Small Business'), ('OASIS', 'OASIS Unrestricted'), ('HCATS_SB', 'HCATS Small Business'), ('HCATS', 'HCATS Unrestricted'), ('BMO_SB', 'BMO Small Business'), ('BMO', 'BMO Unrestricted')], max_length=20),
        ),
    ]
