# Generated by Django 2.0.2 on 2018-04-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20180316_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField()),
                ('naics_code', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
