# Generated by Django 2.0.2 on 2018-04-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_psc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PscNaics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='psc',
            name='naics_code',
        ),
        migrations.AddField(
            model_name='pscnaics',
            name='psc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naics', to='categories.PSC'),
        ),
    ]
