# Generated by Django 2.0.2 on 2018-04-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20180404_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pscnaics',
            name='psc',
        ),
        migrations.AddField(
            model_name='psc',
            name='naics',
            field=models.ManyToManyField(to='categories.Naics'),
        ),
        migrations.DeleteModel(
            name='PscNaics',
        ),
    ]
