# Generated by Django 2.0.2 on 2018-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20180405_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='naics',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='categories.Keyword'),
        ),
        migrations.AddField(
            model_name='psc',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='categories.Keyword'),
        ),
    ]
