# Generated by Django 2.0.2 on 2018-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20180509_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='vehicle',
            field=models.CharField(choices=[('OASIS_SB', 'OASIS Small Business'), ('OASIS', 'OASIS Unrestricted'), ('HCATS_SB', 'HCATS Small Business'), ('HCATS', 'HCATS Unrestricted'), ('BMO_SB', 'BMO Small Business'), ('BMO', 'BMO Unrestricted'), ('PSS', 'Professional Services')], max_length=20),
        ),
    ]
