# Generated by Django 2.0.2 on 2018-06-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20180606_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='naics',
            name='root_code',
        ),
        migrations.RemoveField(
            model_name='psc',
            name='id',
        ),
        migrations.AlterField(
            model_name='naics',
            name='code',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='psc',
            name='code',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
