# Generated by Django 2.0.2 on 2018-06-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20180614_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIN',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('keywords', models.ManyToManyField(blank=True, to='categories.Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='naics',
            name='sin',
            field=models.ManyToManyField(blank=True, to='categories.SIN'),
        ),
        migrations.AddField(
            model_name='psc',
            name='sin',
            field=models.ManyToManyField(blank=True, to='categories.SIN'),
        ),
    ]
