# Generated by Django 2.0.2 on 2018-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20180614_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
