# Generated by Django 2.0.2 on 2018-06-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_auto_20180614_0706'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE categories_naics_keywords ALTER naics_id TYPE varchar(25);"),
        migrations.RunSQL("ALTER TABLE categories_psc_keywords ALTER psc_id TYPE varchar(25);"),
    ]
