# Generated by Django 2.0.2 on 2018-06-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_auto_20180614_0748'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE categories_pool_naics ALTER naics_id TYPE varchar(25);"),
        
        migrations.RunSQL("ALTER TABLE categories_psc_naics ALTER naics_id TYPE varchar(25);"),
        migrations.RunSQL("ALTER TABLE categories_psc_naics ALTER psc_id TYPE varchar(25);"),
    ]
