# Generated by Django 2.0.2 on 2018-06-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_auto_20180614_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
