# Generated by Django 2.0.2 on 2018-08-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_auto_20180618_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='zonestate',
            name='zone',
        ),
        migrations.AlterField(
            model_name='pool',
            name='vehicle',
            field=models.CharField(choices=[('OASIS_SB', 'OASIS Small Business'), ('OASIS', 'OASIS Unrestricted'), ('HCATS_SB', 'HCATS Small Business'), ('HCATS', 'HCATS Unrestricted'), ('BMO_SB', 'BMO Small Business'), ('BMO', 'BMO Unrestricted'), ('PSS', 'Professional Services Schedule')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ZoneState',
        ),
        migrations.AddField(
            model_name='zone',
            name='states',
            field=models.ManyToManyField(blank=True, to='categories.State'),
        ),
    ]
