# Generated by Django 2.0.2 on 2018-08-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Vehicle'),
        ),
    ]
