# Generated by Django 2.0.2 on 2018-09-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_remove_psc_naics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sin',
            name='keywords',
        ),
    ]
