# Generated by Django 2.0.2 on 2018-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_remove_sin_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naics',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='psc',
            name='keywords',
        ),
        migrations.AddField(
            model_name='pool',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='categories.Keyword'),
        ),
    ]
