# Generated by Django 2.0.2 on 2018-09-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_auto_20180918_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='calc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='naics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Naics'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Keyword'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='psc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.PSC'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='sin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.SIN'),
        ),
    ]
