# Generated by Django 2.0.9 on 2018-11-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0024_auto_20180918_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='calc',
            field=models.CharField(db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(db_index=True, default='Pool', max_length=128),
        ),
        migrations.AlterField(
            model_name='pool',
            name='number',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='setaside',
            name='far_order',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='setaside',
            name='name',
            field=models.CharField(db_index=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
