# Generated by Django 2.0.2 on 2018-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0028_auto_20180211_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='type',
            field=models.CharField(choices=[('CM', 'Contract Manager'), ('PM', 'Project Manager')], max_length=10),
        ),
    ]
