# Generated by Django 2.0.2 on 2018-03-16 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20180316_0232'),
        ('vendors', '0030_auto_20180305_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractManager',
            fields=[
                ('manager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.Manager')),
            ],
            bases=('vendors.manager',),
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('manager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.Manager')),
            ],
            bases=('vendors.manager',),
        ),
        migrations.RemoveField(
            model_name='manager',
            name='type',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='pools',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='setasides',
        ),
        migrations.AddField(
            model_name='poolmembership',
            name='setasides',
            field=models.ManyToManyField(blank=True, to='categories.SetAside'),
        ),
        migrations.AlterField(
            model_name='poolmembership',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='vendors.Vendor'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='responsibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pms', to='vendors.PoolMembership'),
        ),
        migrations.AddField(
            model_name='contractmanager',
            name='responsibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms', to='vendors.PoolMembership'),
        ),
    ]
