# Generated by Django 2.0.2 on 2018-03-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20180316_0232'),
        ('vendors', '0031_auto_20180316_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolmembershipzone',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='poolmembershipzone',
            name='zone',
        ),
        migrations.AddField(
            model_name='poolmembership',
            name='zones',
            field=models.ManyToManyField(blank=True, to='categories.Zone'),
        ),
        migrations.DeleteModel(
            name='PoolMembershipZone',
        ),
    ]
