# Generated by Django 2.0.2 on 2018-03-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0032_auto_20180318_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageremail',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='vendors.Manager'),
        ),
        migrations.AlterField(
            model_name='managerphonenumber',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='vendors.Manager'),
        ),
    ]
