# Generated by Django 2.0.2 on 2018-06-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0033_auto_20180319_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolmembership',
            name='contract_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='poolmembership',
            name='expiration_8a_date',
            field=models.DateTimeField(null=True),
        ),
    ]
