# Generated by Django 2.0.2 on 2018-07-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0035_auto_20180606_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samload',
            old_name='sam_load',
            new_name='load_date',
        ),
        migrations.AddField(
            model_name='samload',
            name='vendor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
