# Generated by Django 2.0.2 on 2018-08-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0036_auto_20180711_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('responsibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='vendors.PoolMembership')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='vendors.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='vendors.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='contractmanager',
            name='manager_ptr',
        ),
        migrations.RemoveField(
            model_name='contractmanager',
            name='responsibility',
        ),
        migrations.RemoveField(
            model_name='manageremail',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managerphonenumber',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='manager_ptr',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='responsibility',
        ),
        migrations.DeleteModel(
            name='ContractManager',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='ManagerEmail',
        ),
        migrations.DeleteModel(
            name='ManagerPhoneNumber',
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
