# Generated by Django 2.0.2 on 2018-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0037_auto_20180802_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
