# Generated by Django 2.0.2 on 2018-08-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0038_contact_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samload',
            name='load_date',
        ),
        migrations.AddField(
            model_name='samload',
            name='load_time',
            field=models.DateTimeField(null=True),
        ),
    ]
