# Generated by Django 2.0.9 on 2018-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0039_auto_20180806_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='address',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='number',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='congressional_district',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='poolmembership',
            name='contract_end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='poolmembership',
            name='expiration_8a_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='samload',
            name='load_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cage',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='duns',
            field=models.CharField(db_index=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='duns_4',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sam_activation_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sam_exclusion',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sam_expiration_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sam_status',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
