# Generated by Django 2.0.9 on 2018-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_cachepage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachepage',
            name='count',
            field=models.BigIntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cachepage',
            name='url',
            field=models.URLField(db_index=True, max_length=2083, unique=True),
        ),
    ]
