# Generated by Django 2.0.2 on 2018-03-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_contractstatus_pricingstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.ContractStatus'),
        ),
        migrations.RunSQL("UPDATE contracts_contract SET status_id = reason_for_modification;"),
        migrations.RemoveField(
            model_name='contract',
            name='reason_for_modification',
        ),
        migrations.AlterField(
            model_name='contract',
            name='pricing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.PricingStructure'),
        ),
    ]
