# Generated by Django 2.0.2 on 2018-05-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_auto_20180301_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='base_piid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        )
    ]
