# Generated by Django 2.0.2 on 2018-05-22 19:09

from django.db import migrations, models


def create_base_piids(apps, schema_editor):
    Contract = apps.get_model('contracts', 'Contract')
    
    for contract in Contract.objects.all():
        contract.base_piid = contract.piid.split('_')[0]
        contract.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_auto_20180301_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='base_piid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.RunPython(create_base_piids),
    ]
