# Generated by Django 2.0.9 on 2018-10-17 00:34

from django.db import migrations, models
import django.db.models.deletion


def copy_agency_ids(apps, schema_editor):
    Contract = apps.get_model('contracts', 'Contract')
    
    for contract in Contract.objects.all().iterator():
        contract.agency_id_backup = contract.agency_id
        contract.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_contract_base_piid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='agency_id_backup',
            field=models.CharField(max_length=128, null=True, serialize=False),
        ),
        migrations.RunPython(copy_agency_ids),
        migrations.RemoveField(
            model_name='contract',
            name='agency_id',
        ),
    ]
