# Generated by Django 2.0.9 on 2018-11-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_auto_20181017_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='number_of_employees',
        ),
    ]
